### PR TITLE
Change api.js

### PR DESCRIPTION
**Pull request by IDK-TERADA**
Added logic to dynamically initialize outputs[videoChannel] and outputs[audioChannel] if they are undefined.

Target file: api.js, 
lines: 91 and 104.

### CODE REVIEW

**Comment by josephdadams** [comment]
This is already done in constants.js so I’m not sure this is necessary

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-idk-ninjar/issues/3#issuecomment-2452731585

**Comment by IDK-TERADA** [comment]
I took a look at index.js, and it has the following code:

// Assign the methods from the listed files to this class
Object.assign(this, {
    ...config,

    ...actions,
    ...feedbacks,
    ...variables,
    ...presets,

    ...api,

    ...constants,
})
}
Could it be an issue with the order in Object.assign?

**Comment by josephdadams** [comment]
I wouldn't think so because they still aren't accessed until later in the module workflow, but you are welcome to try swapping the order.

**Pull request merged**
